name: Test And Lint Podspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Set simulator
      id: simulator
      run: echo ::set-output name=PHONE_ID::$(instruments -s devices | grep -m 1 'iPhone 8' | awk -F'[][]' '{print $2}')
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,id=${{ steps.simulator.outputs.PHONE_ID }}'
        additional_lint_params: --allow-warnings
