name: Test And Lint Podspec

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependences
      run: |
        cd Example
        pod repo update
        pod install
      shell: bash
    - name: Test and Lint
      uses: ty0x2333/cocoapods-action@master
      with:
        additional_build_params: -destination 'platform=iOS Simulator,id=F37D3091-C3D4-4652-859D-901F18F2AF8D'
        additional_lint_params: --allow-warnings
